config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "costumes#index"

  resources :costumes do
    collection do
      get "mycostumes"
    end
    resources :bookings, only: [:create]
  end
  resources :bookings, only: [:index]

  get '/faq', to: 'pages#faq'
  get '/contact', to: 'pages#contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :costume

  validates :end_date, :start_date, presence: true
  validate :end_date_is_after_start_date
  validate :no_overlapping_booking

  private

  def end_date_is_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date

      errors.add(:end_date, "must be equal to or later than the start date")

    end
  end

  def no_overlapping_booking
    return if end_date.blank? || start_date.blank?

    overlapping_booking = Booking.where(costume_id: costume_id).where("start_date < ? AND end_date > ?", end_date, start_date).where.not(id: id)

    if overlapping_booking.exists?
      errors.add(:end_date, "Booking overlaps with an existing booking")
    end
  end
end

app/models/costume.rb
class Costume < ApplicationRecord
  has_many :bookings, dependent: :destroy
  belongs_to :user

  validates :title, :description, :details, :price_per_day, :size, :category, presence: true
  validates :description, length: { minimum: 6 }

  has_many_attached :photos

  include PgSearch::Model
    pg_search_scope :search_by_title_and_description_and_category,
      against: [ :title, :description, :category ],
      using: {
        tsearch: { prefix: true } # <-- now `superman batm` will return something!
      }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings, dependent: :destroy
  has_many :costumes, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :address, presence: true
  validates :email, format: { with: Devise.email_regexp }, presence: true
  validates :password, presence: true, length: { minimum: 6 }, format: { with: /(?=.*[a-z])(?=.*[A-Z])(?=.*\d)/ }
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :email, :address, :phone_number, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
require 'date'

class BookingsController < ApplicationController

  def create
    @costume = Costume.find(params[:costume_id])
    @user = current_user

    @booking = Booking.new(booking_params)
    @booking.costume = @costume
    @booking.user = @user
    @booking.total_price = @booking.costume.price_per_day * amount_of_days

    if @booking.save!
      redirect_to bookings_path(booking_id: @booking.id)
    else
      flash.now[:alert] = 'Your booking was not successful. Make sure the end date is after the start date!'
      render 'costumes/show', status: :unprocessable_entity
    end
  end

  def index
    @bookings = current_user.bookings.order(start_date: :asc)
    @booking = @bookings.detect { |booking| booking.id == params[:booking_id].to_i }
  end

  private

  def booking_params
    attributes = {
    }
    permitted_params = params.require(:booking).permit(:start_date)
    attributes[:start_date] = permitted_params[:start_date].gsub(/ to .*/, '').to_date
    attributes[:end_date] = permitted_params[:start_date].gsub(/.* to /, "").to_date

    return attributes
  end

  def amount_of_days
    start_date = @booking.start_date.to_date
    end_date = @booking.end_date.to_date

    diff_date = (end_date - start_date).to_i
    diff_date.zero? ? 1 : diff_date
  end
end

app/controllers/costumes_controller.rb
class CostumesController < ApplicationController
  before_action :find_user, only: %i[show edit mycostumes]
  before_action :find_costume, only: %i[update destroy show edit]
  skip_before_action :authenticate_user!, only: :index

def index
  if params[:dates].present?
    dates = params[:dates].split(' to ')
    start_date = dates.first.to_date
    end_date = dates.last.to_date + 1.day
  end
  if dates.present?
    @forbidden_bookings = Booking.select(:costume_id).where(start_date: start_date..end_date).or(Booking.where(end_date: start_date..end_date))
    @costumes = Costume.where.not(id: @forbidden_bookings)
  end
  @costumes ||= Costume.all
  if params[:query].present?
    @costumes = @costumes.search_by_title_and_description_and_category(params[:query])
  end
end

  def show
    @booking = Booking.new
    @bookings_dates = @costume.bookings.map do |booking|
      {
        from: booking.start_date,
        to: booking.end_date
      }
    end

    @price_per_day = @costume.price_per_day.to_f
  end

  def new
    @costume = Costume.new
    @costume_categories = [
      "Animal", "Superhero", "Fantasy", "Horror", "Historical",
      "Sci-Fi", "Pirate", "Disney", "Fairy Tale", "Zombie",
      "Vampire", "Alien", "Steampunk", "Celebrity", "Cartoon",
      "Clown", "Sports", "Medieval", "Victorian", "Greek Mythology",
      "Roman Mythology", "Ninja", "Samurai", "Military", "Western",
      "Space", "Sea Creature", "Robot", "Wizard", "Witch"
    ]
  end

  def create
    costume = Costume.new(costume_params)
    costume.user = current_user
    if costume.save!
      redirect_to costume_path(costume)
    else
      render :index, status: :unprocessable_entity
    end
  end

  def edit
    @costume_categories = [
      "Animal", "Superhero", "Fantasy", "Horror", "Historical",
      "Sci-Fi", "Fairy Tale", "Zombie",
      "Vampire", "Alien", "Steampunk", "Celebrity", "Cartoon",
      "Clown", "Victorian", "Greek Mythology",
      "Roman Mythology", "Ninja", "Samurai", "Military", "Western",
      "Robot", "Wizard", "Witch"
    ]
  end

  def update
    if @costume.update(costume_params)
      redirect_to costume_path(@costume), notice: 'Costume was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @costume.destroy
    redirect_to costume_path(@costume), status: :see_other
  end

  def mycostumes
    @costumes = @user.costumes
  end

  private

  def find_user
    @user = current_user
  end

  def find_costume
    @costume = Costume.find(params[:id])
  end

  def costume_params
    params.require(:costume).permit(:title, :description, :price_per_day, :size, :category, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

  def contact
  end

  def faq
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="card-category-smaller custom-banner" style="background-image: url('<%= asset_path("mario.jpg") %>'); object-fit: top;">
  All of your bookings, <%= current_user.first_name %>!
</div>

<div class="container">
  <div class="d-flex justify-content-between">
      <h4 class="mt-4"><strong>Booking history (<%= @bookings.count %>) </strong></h4>
      <%= link_to 'Book a new costume', costumes_path, class: "btn btn-dark mt-4 rounded" %>
  </div>
  <hr>
</div>

<% if @booking.present? %>
  <div class="container">
    <div class="alert alert-success" role="alert">
      Your new booking was successfully registered. Have fun!
    </div>
  </div>
<% end %>

<div class="container">
  <div class="grid-container">
    <% @bookings.each do |booking| %>
      <div class= "card">
        <div class ="card-image">
          <% if booking.costume.photos.attached? %>
              <% photo = booking.costume.photos[0] %>
              <%= cl_image_tag photo.key, alt: "Costume picture", class: "card-photo", style: "width:90%; object-fit:cover" %>
          <% else %>
                <%= image_tag "girl.jpg", alt: "girl picture", class: "card-photo", style: "width:90%; object-fit:cover" %>
          <% end %>
        </div>

        <div class="card-info">
          <h5 class="card-title"><%= link_to booking.costume.title, costume_path(booking.costume) %></h5>
          <div>
            <p> <b>From: </b> <%= booking.start_date.strftime("%B %d, %Y") %></p>
            <p> <b>Until: </b> <%= booking.end_date.strftime("%B %d, %Y") %></p>
            <p><%= booking.total_price %> €</p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/costumes/_form.html.erb
  <%= simple_form_for(@costume) do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :price_per_day %>
    <%= f.input :size, collection: ["Extra small", "Small","Medium","Large", "Extra Large"] %>
    <%= f.input :category, collection: @costume_categories, prompt: 'Select Category' %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.submit class: "btn btn-primary mt-2"%>
  <% end %>

app/views/costumes/edit.html.erb
<div class="container mt-3 w-50">
  <h3>Update your costume</h3>
  <%= render "form", costume: @costume %>
</div>

app/views/costumes/index.html.erb
<div class = "body">
  <div class ="banner d-flex flex-column">
      <H1>Turn heads, crack up crowds</H1>
      <div class="search container">
        <div class="row justify-content-center">
          <div class="col-sm-8 my-3">
            <%= form_with url: root_path, method: :get, id: "search-form", class: "d-flex bg-light rounded" do %>
              <%= text_field_tag :query,
                    params[:query],
                    class: "form-control",
                    placeholder: "What do you want to turn into?"
                %>
              <%= label_tag :dates, "", class: "form-label" %>
              <%= text_field_tag :dates, nil, value: params[:dates], class: "form-control", data: { controller: "datepicker", input: true }, placeholder: "When?"%>
              <%= button_tag "", name: "", class: "btn btn-light" do %><i class="fa-solid fa-magnifying-glass"></i><% end %>
            <% end %>
          </div>
        </div>
      </div>
  </div>
  <div class = "container">
    <% unless @costumes.present? %>
        <div class="flash flash-danger alert alert-dismissible fade show" role="alert">
          <span><strong>Oops!</strong> 😱 The costume you are looking for is not available at that time.</span>
          <a data-bs-dismiss="alert" aria-label="Close">
            <i class="fas fa-times"></i>
          </a>
        </div>
    <% end %>
    <div class="grid-container">
      <% @costumes.each do |costume| %>
          <div class= "card">
            <div class ="card-image">

              <% if costume.photos.attached? %>
                <% photo = costume.photos[0] %>
                <%= cl_image_tag photo.key, alt: "Costume picture", class: "card-photo", style: "width:90%; object-fit:cover" %>

              <% else %>
                <%= image_tag "girl.jpg", alt: "girl picture", class: "card-photo", style: "width:90%" %>
              <% end %>
            </div>

            <div class="card-info mb-3">

              <h6 class="card-title"><%= link_to costume.title, costume_path(costume) %></h6>
              <p><%= costume.description %></p>

              <div class="card-details">

                <div class="card-user-avatar">
                  <%= cl_image_tag costume.user.photo.key, height: 25, width: 25, crop: :fill %>
                  <h6 class="ml-2"><%= costume.user.first_name.split(" ")[0] %></h6>
                </div>
                <p><strong><%= costume.price_per_day %> €</strong></p>

              </div>

            </div>

          </div>
      <% end %>

    </div>
  </div>
</div>

app/views/costumes/mycostumes.html.erb
<div class="card-category-smaller" style="background-image: url('<%= asset_path("my_costumes.jpg") %>'); background-size: cover; background-position: center; background-repeat: no-repeat; height: 300px;">
  Here are your costumes, <%= current_user.first_name %>! 👻
</div>

<div class="container">
  <div class="d-flex justify-content-between">
      <h4 class="mt-4"><strong>My beautiful costumes (<%= @costumes.count %>)</strong></h4>
      <%= link_to 'Add a new costume', new_costume_path, class: "btn btn-dark mt-4 rounded" %>
  </div>
  <hr>
</div>

<div class="container">
  <div class="grid-container">
    <% @costumes.each do |costume| %>
      <div class="card">
        <div class="card-image">
          <% if costume.photos.attached? %>
            <% photo = costume.photos[0] %>
            <%= cl_image_tag photo.key, alt: "Costume picture", class: "card-photo", style: "width:90%; object-fit:cover" %>
          <% else %>
            <%= image_tag "girl.jpg", alt: "girl picture", class: "card-photo", style: "width:90%" %>
          <% end %>
        </div>
        <div class="card-info">
          <h6 class="card-title"><strong><%= link_to costume.title, costume_path(costume) %></strong></h6>
          <p><strong>Description: </strong><%= costume.description %></p>
          <p><strong>Price: </strong><%= costume.price_per_day %>€</p>
        </div>
        <div class="d-flex justify-content-end p-1 w-100">
          <%= link_to edit_costume_path(costume), class: "ml-4 p-2 text-dark" do %>
            <i class="fa-solid fa-pencil"></i>
          <% end %>
          <%= link_to costume_path(costume.id), data: { turbo_method: :delete, turbo_confirm: "Are you sure???" }, class: "p-2 text-dark" do %>
            <i class="fa-solid fa-trash-can"></i>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/costumes/new.html.erb
<div class="container mt-3 w-50">
  <h3>Upload your costume</h3>
  <%= render 'form' %>
</div>

app/views/costumes/show.html.erb
<div class="show-container">

    <div class = "show-card">

      <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">

        <div class="carousel-inner">

          <div class="carousel-item active">
            <%= cl_image_tag @costume.photos[0].key, height: 450, width: 500, class: "d-block w-10 img-show-carroussel" %>
          </div>
          <div class="carousel-item">
            <%= cl_image_tag @costume.photos[1].key, height: 450, width: 500, class: "d-block w-10 img-show-carroussel" %>
          </div>
          <div class="carousel-item">
            <%= cl_image_tag @costume.photos[2].key, height: 450, width: 500, class: "d-block w-10 img-show-carroussel" %>
          </div>

        </div>

        <button class="carousel-control-prev" type="button"  data-bs-target="#carouselExampleControls" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>

        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>

      </div>

      <div class ="show-card-info">

        <div class = "show-card-text mt-2 pr-4">
          <h4 class= "pb-3 pt-1"><%= @costume.title %></h4>
          <h6 class= "pb-3"><%= @costume.details %></h6>
          <h6><b>Size: </b><%= @costume.size %></h6>
          <h6><b>Category: </b><%= @costume.category %></h6>
        </div>

        <div class="show-card-details">

          <div class="show-card-user-avatar">
              <%= cl_image_tag @costume.user.photo.key, height: 25, width: 25, crop: :fill %>
              <p><%= @costume.user.first_name.split(" ")[0]%></p>
          </div>

          <p class="pr-6"><strong><%=@costume.price_per_day %> €</strong></p>

        </div>

      </div>

    </div>

  <div>

 <div id="booking-form" class="p-3" data-bookings-dates="<%= @bookings_dates.to_json %>" data-price-per-day="<%= @costume.price_per_day %>">
        <h3>Book this costume</h3>
      <%= simple_form_for [@costume, @booking] do |f| %>
          <%= f.input :start_date, as: :string, input_html: { id: "start_date", data: { controller: "booking-datepicker" },class: "d-none" }, label: false %>
          <%= f.button :submit, "Book this costume", class: "btn btn-primary" %>
      <% end %>
        <h6 class="mt-3"> <b>Total price: <span id="total-price">€</b></span></h6>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CosplayCorner</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="icon" type="image/png" sizes="48x48" href="<%= asset_path('favicon.png') %>">
  </head>

  <body>
    <%= render 'shared/navbar2' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/contact.html.erb
<div class="container" style="margin-bottom: 130px">
  <h3 class="mt-3">Feel free to contact us 💖</h3>
  <div class="col-md-6 mt-3">
    <h5><b>Email</b></h5>
    <p>support@cosplaycorner.com</p>
    <h5><b>Phone</b></h5>
    <p>(123) 456-7890</p>
  </div>

  <div class="col-md-6">
    <h5><b>Frequently Asked Questions</b></h5>
    <p>Check out our <%= link_to 'FAQ page', faq_path %> for quick answers to common questions.</p>
  </div>
</div>

app/views/pages/faq.html.erb
<div class="container">
  <h3 class="mt-3">Frequently Asked Questions</h6>

  <div class="faq-item">
    <h6 class="question">Q: Are these your costumes?</h6>
    <p>A: Nope! We’re just the matchmakers. Our amazing users have the costumes, and they’re eager to share!</p>
  </div>

  <div class="faq-item">
    <h6 class="question">Q: What if I accidentally spill coffee on a costume?</h6>
    <p>A: Uh-oh! Don’t worry, we’ve seen worse. Just let the lender know and try to wash it out with tears of regret.</p>
  </div>

  <div class="faq-item">
    <h6 class="question">Q: Can I wear a costume to a wedding? Asking for a friend.</h6>
    <p>A: You do you! Just make sure to RSVP as you and not your alter ego. We’ve seen some confused brides before.</p>
  </div>

  <div class="faq-item">
    <h6 class="question">Q: Do the costumes come with snacks?</h6>
    <p>A: Sorry, no snacks included! You’ll have to smuggle your own candy bars, or settle for cosmic superhero power instead.</p>
  </div>

  <div class="faq-item">
    <h6 class="question">Q: Can I join this costume party? I’m 4,337 miles away.</h6>
    <p>A: Sure, but only if you teleport. We recommend a superhero costume for that, not a regular one. Good luck!</p>
  </div>

  <div class="faq-item">
    <h6 class="question">Q: How do I get a refund for the costume that made my cat mad?</h6>
    <p>A: Just send the costume back in the condition you got it, including any new claw marks. We’ll handle the rest.</p>
  </div>

  <div class="faq-item">
    <h6 class="question">Q: I want to be a superhero. Which costume has the most powers?</h6>
    <p>A: Good question! They all have the same power level: awesome. Choose wisely, and be ready to save the day!</p>
  </div>

  <div class="faq-item">
    <h6 class="question">Q: Can I keep the costume if I love it too much to give it back?</h6>
    <p>A: Aw, we understand! But you gotta share. Renting is caring, after all.</p>
  </div>

  <div class="faq-item">
    <h6 class="question">Q: What if I accidentally summon an ancient curse with the costume?</h6>
    <p>A: If that happens, please call your local Ghostbusters. Don’t worry, you won’t be charged extra for the curse!</p>
  </div>


  <div class="faq-item">
    <h6 class="question">Q: Can I rent a costume for my pet llama? His name is Carl.</h6>
    <p>A: Sure thing, Carl deserves to party too! Just make sure the costume fits his fabulousness.</p>
  </div>

</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_footer.html.erb
<div class="bg-light text-dark mt-4">
  <div class="d-flex justify-content-center">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "CosplayCorner1.svg", alt: "CosplayCorner", width: 200, class: "logo" %>
    <% end %>
  </div>
  <div class="d-flex justify-content-center pb-3">
    <%= link_to faq_path, class: "text-dark mx-3" do %>
      <i class="fa-regular fa-circle-question"></i>
    <% end %>
    <%= link_to contact_path, class: "text-dark mx-3" do %>
      <i class="fa-solid fa-envelope"></i>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <div class="navbar-container">
    <%= link_to costumes_path, class: "navbar-brand" do %>
      <%= image_tag "CosplayCorner.svg",alt: "CosplayCorner", width: 200, class: "logo" %>
    <% end %>
    <div class="navlink-holder">
      <%= link_to "Add a costume", costumes_path, class: "nav-link" %>
      <%= link_to "My Costumes", mycostumes_costumes_path, class: "nav-link" %>
      <%= link_to "My Bookings", bookings_path, class: "nav-link" %>
    </div>
  </div>
</div>

app/views/shared/_navbar2.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to costumes_path, class: "navbar-brand" do %>
      <%= image_tag "CosplayCorner1.svg", alt: "CosplayCorner", width: 200, class: "logo" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Add a costume", new_costume_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My costumes", mycostumes_costumes_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My bookings", bookings_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: { turbo_method: :delete } %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link btn btn-dark rounded" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link btn btn-light rounded ml-2" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/footer.html.erb
<div class="mt-auto p-3 bg-light text-dark">
  <div class="d-flex justify-content-center">
    <a href="https://www.linkedin.com/in/brunacaricio/" class="text-dark mx-3" target="_blank">
      <i class="fa-brands fa-linkedin fs-3"></i>
    </a>
    <a href="https://github.com/brunacaricio" class="text-dark mx-3" target="_blank">
      <i class="fa-brands fa-github fs-3"></i>
    </a>
  </div>
</div>